version: "3.8"

services:
  frontend:
    build:
      context: ./FE
      args:
        # env variables for FE
        VITE_BASE_URL: ${VITE_BASE_URL}
    container_name: todo-frontend
    ports:
      - "3000:80" # port 80 in container served by nginx -> exposed on 3000
    restart: unless-stopped

  backend:
    build:
      context: ./BE
      args:
        DATABASE_URL: file:./dev.db
        JWT_SECRET: ${JWT_SECRET}
    container_name: todo-backend
    ports:
      - "3001:3001"
    volumes:
      - sqlite_data:/app/prisma/data
    env_file:
      - ./BE/.env
    restart: unless-stopped

volumes:
  sqlite_data:
    name: sqlite_data
