version: "3.8"

services:
  backend:
    build: ./BE
    container_name: todo-backend
    ports:
      - "3001:3001"
    volumes:
      - ./BE:/app
      - ./data/sqlite:/app/prisma/data
    env_file:
      - ./BE/.env
    restart: unless-stopped
